services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './docker/laravel/init-migrate.sh:/init-migrate.sh'
        entrypoint: ["/init-migrate.sh"]
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST_WRITE}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './docker/mysql/conf.d/z-replication.cnf:/etc/mysql/conf.d/z-replication.cnf'
            - './docker/mysql/init-replica-user.sql:/docker-entrypoint-initdb.d/99-init-replica-user.sql'
        networks:
            - sail
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
            retries: 3
            timeout: 5s

    mysql_read:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_READ_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST_READ}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql-read:/var/lib/mysql'
            - './docker/mysql_read/conf.d/z-replication.cnf:/etc/mysql/conf.d/z-replication.cnf'
            - './docker/mysql_read/init-replication.sh:/docker-entrypoint-initdb.d/99-init-replication.sh'
            - './docker/mysql_read/init-sail-user.sql:/docker-entrypoint-initdb.d/99-init-sail-user.sql'
        networks:
            - sail
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
            retries: 3
            timeout: 5s
        depends_on:
            mysql:
                condition: service_healthy

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-mysql-read:
        driver: local
